name: easypaisa_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  confetti: ^0.7.0    # For the animation
  intl: ^0.19.0       # For the DateFormat in HistoryScreen
  mobile_scanner: ^5.1.0
  google_fonts: ^6.1.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# PAY ATTENTION TO THE SPACES BELOW
# In your pubspec.yaml
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/frames/
    - assets/confetti_frames/
    - assets/home_bg.jpg
    - assets/send_menu_bg.png
    - assets/settings_bg.jpg
    - assets/ep_cl.webp
    - assets/wallet_ik.png
    - assets/sounds/